service: grokit-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-2

functions:
  projects:
    handler: handler.projects
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http: 
          path: projects
          method: get
          cors: true
      - http: 
          path: projects/{projectId}/skillToDo
          method: get
          cors: true
  skills:  
    handler: handler.skills
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http: 
          path: skills
          method: get
          cors: true
      - http: 
          path: skills/{skillId}/markAsPractised
          method: put
          cors: true